// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vappparmqrnubzrjswpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhcHBwYXJtcXJudWJ6cmpzd3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjIxMTEsImV4cCI6MjA2MTQzODExMX0.-hV5EvU5SfHCIAytm3eKI88JF51IS41KEx2taJrrFGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);